version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing cfn-lint...
      - pip install cfn-lint
      - echo Installing Node.js dependencies...
      - npm install

  build:
    commands:
      - echo Linting CloudFormation template...
      - cfn-lint template.yml
      - cp template.yml output.yml
      - echo Build phase complete
      - echo Zipping file for lambda function
      - zip -r LambdaFunction.zip node_modules
      - echo Setting S3 bucket name...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - BUCKET_NAME="minimal-informer-codepipeline-artifacts-${ACCOUNT_ID}-${AWS_REGION}"
      - echo Uploading 'init' folder to $BUCKET_NAME...
      - aws s3 cp ./website_layout s3://$BUCKET_NAME/StaticWebsite/ --recursive
      - echo Zipping npm install for lambda dependencies
      - zip -r node_modules.zip node_modules/
      - echo Pushing zip file to bucket
      - aws s3 cp node_modules.zip s3://$BUCKET_NAME/node_modules.zip

artifacts:
  name: BuildOutput
  files:
    - output.yml  
    - node_modules.zip
  discard-paths: yes