---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  TableName:
    Description: Name for DynamoDb Table
    Type: String
    Default: news-data


Globals:
  globally available functions
  
Mappings:
  set of mappings

Conditions:
  set of conditions

Resources:
  news-table:
    Type: AWS::DynamoDB:Table
    Properties: 
      TableName: !Ref TableName
  
  NewsFetchMachineRole:
    Type: AWS::IAM::Role
    Properties:

Outputs:
  set of outputs
