---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  TableName:
    Description: Name for DynamoDb Table
    Type: String
    Default: news-data
  
  BucketPrefix:
    Description: Name of S3 Bucket 
    Type: String
    Default: minimal-informer-codepipeline-artifacts

  LambdaCodeKey:
    Type: String
    Description: Path to the ZIP file inside the bucket
    Default: node_modules.zip
  
  # LambdaCodeVersion:
  #   Type: String
  #   Description: Version of the lambda.zip file to keep code in aws up to date built via buildspec
  #   Default: '{{resolve:ssm:/MyApp/LambdaVersion}}'

Resources:
  NewsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Role Creation
  NewsFetchMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: "*"

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName:  StateMachineLambdaInvoke
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow 
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
  # Lambda Function Definition
  WorldNewsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BasicLambdaExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetObject
                  - ssm:GetParameter
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: "*"

  NodeModulesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: NodeModulesLayer
      Content:
        S3Bucket: !Sub "${BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
        S3Key: !Sub "${LambdaCodeKey}"
      CompatibleRuntimes:
        - nodejs18.x

  #Function Creation
  WorldNewsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WorldNewsFunction
      Handler: functions/world-news.handler
      Runtime: nodejs18.x
      Role: !GetAtt WorldNewsFunctionRole.Arn
      Code:
        S3Bucket: !Sub "${BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
        S3Key: lambdafunctions.zip
        S3ObjectVersion: '{{resolve:ssm:/MyApp/LambdaVersion}}'
      MemorySize: 128
      Timeout: 5
      Layers:
        - !Ref NodeModulesLayer  # Referencing the Lambda Layer
      Environment:
        Variables:
          BUCKET_NAME: !Sub "${BucketPrefix}-${AWS::AccountId}-${AWS::Region}"
          LAMBDA_ZIP_KEY: !Sub "${LambdaCodeKey}"  # The key to the node_modules.zip file in S3

  # State machine definition
  MyStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      RoleArn: !GetAtt StateMachineRole.Arn
      DefinitionString:
        Fn::Sub: |
            {
              "Comment": "State machine to fetch news",
              "StartAt": "FetchNews",
              "States": {
                "FetchNews": {
                  "Type": "Task",
                  "Resource": "${WorldNewsFunction.Arn}",
                  "End": true
                }
              }
            }

# Outputs:
#   set of outputs
